// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marionet.proto

#ifndef PROTOBUF_marionet_2eproto__INCLUDED
#define PROTOBUF_marionet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_marionet_2eproto();
void protobuf_AssignDesc_marionet_2eproto();
void protobuf_ShutdownFile_marionet_2eproto();

class MarkovInput;
class FutureProto;
class PlayFunRequest;
class PlayFunResponse;
class TryImproveRequest;
class TryImproveResponse;
class HelperRequest;

enum TryImproveRequest_Approach {
  TryImproveRequest_Approach_RANDOM = 0,
  TryImproveRequest_Approach_OPPOSITES = 1,
  TryImproveRequest_Approach_ABLATION = 2,
  TryImproveRequest_Approach_CHOP = 3
};
bool TryImproveRequest_Approach_IsValid(int value);
const TryImproveRequest_Approach TryImproveRequest_Approach_Approach_MIN = TryImproveRequest_Approach_RANDOM;
const TryImproveRequest_Approach TryImproveRequest_Approach_Approach_MAX = TryImproveRequest_Approach_CHOP;
const int TryImproveRequest_Approach_Approach_ARRAYSIZE = TryImproveRequest_Approach_Approach_MAX + 1;

const ::google::protobuf::EnumDescriptor* TryImproveRequest_Approach_descriptor();
inline const ::std::string& TryImproveRequest_Approach_Name(TryImproveRequest_Approach value) {
  return ::google::protobuf::internal::NameOfEnum(
    TryImproveRequest_Approach_descriptor(), value);
}
inline bool TryImproveRequest_Approach_Parse(
    const ::std::string& name, TryImproveRequest_Approach* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TryImproveRequest_Approach>(
    TryImproveRequest_Approach_descriptor(), name, value);
}
// ===================================================================

class MarkovInput : public ::google::protobuf::Message {
 public:
  MarkovInput();
  virtual ~MarkovInput();

  MarkovInput(const MarkovInput& from);

  inline MarkovInput& operator=(const MarkovInput& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MarkovInput& default_instance();

  void Swap(MarkovInput* other);

  // implements Message ----------------------------------------------

  MarkovInput* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MarkovInput& from);
  void MergeFrom(const MarkovInput& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:MarkovInput)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_marionet_2eproto();
  friend void protobuf_AssignDesc_marionet_2eproto();
  friend void protobuf_ShutdownFile_marionet_2eproto();

  void InitAsDefaultInstance();
  static MarkovInput* default_instance_;
};
// -------------------------------------------------------------------

class FutureProto : public ::google::protobuf::Message {
 public:
  FutureProto();
  virtual ~FutureProto();

  FutureProto(const FutureProto& from);

  inline FutureProto& operator=(const FutureProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FutureProto& default_instance();

  void Swap(FutureProto* other);

  // implements Message ----------------------------------------------

  FutureProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FutureProto& from);
  void MergeFrom(const FutureProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes inputs = 4;
  inline bool has_inputs() const;
  inline void clear_inputs();
  static const int kInputsFieldNumber = 4;
  inline const ::std::string& inputs() const;
  inline void set_inputs(const ::std::string& value);
  inline void set_inputs(const char* value);
  inline void set_inputs(const void* value, size_t size);
  inline ::std::string* mutable_inputs();
  inline ::std::string* release_inputs();
  inline void set_allocated_inputs(::std::string* inputs);

  // @@protoc_insertion_point(class_scope:FutureProto)
 private:
  inline void set_has_inputs();
  inline void clear_has_inputs();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* inputs_;
  friend void  protobuf_AddDesc_marionet_2eproto();
  friend void protobuf_AssignDesc_marionet_2eproto();
  friend void protobuf_ShutdownFile_marionet_2eproto();

  void InitAsDefaultInstance();
  static FutureProto* default_instance_;
};
// -------------------------------------------------------------------

class PlayFunRequest : public ::google::protobuf::Message {
 public:
  PlayFunRequest();
  virtual ~PlayFunRequest();

  PlayFunRequest(const PlayFunRequest& from);

  inline PlayFunRequest& operator=(const PlayFunRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayFunRequest& default_instance();

  void Swap(PlayFunRequest* other);

  // implements Message ----------------------------------------------

  PlayFunRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayFunRequest& from);
  void MergeFrom(const PlayFunRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes current_state = 1;
  inline bool has_current_state() const;
  inline void clear_current_state();
  static const int kCurrentStateFieldNumber = 1;
  inline const ::std::string& current_state() const;
  inline void set_current_state(const ::std::string& value);
  inline void set_current_state(const char* value);
  inline void set_current_state(const void* value, size_t size);
  inline ::std::string* mutable_current_state();
  inline ::std::string* release_current_state();
  inline void set_allocated_current_state(::std::string* current_state);

  // optional bytes next = 2;
  inline bool has_next() const;
  inline void clear_next();
  static const int kNextFieldNumber = 2;
  inline const ::std::string& next() const;
  inline void set_next(const ::std::string& value);
  inline void set_next(const char* value);
  inline void set_next(const void* value, size_t size);
  inline ::std::string* mutable_next();
  inline ::std::string* release_next();
  inline void set_allocated_next(::std::string* next);

  // repeated .FutureProto futures = 3;
  inline int futures_size() const;
  inline void clear_futures();
  static const int kFuturesFieldNumber = 3;
  inline const ::FutureProto& futures(int index) const;
  inline ::FutureProto* mutable_futures(int index);
  inline ::FutureProto* add_futures();
  inline const ::google::protobuf::RepeatedPtrField< ::FutureProto >&
      futures() const;
  inline ::google::protobuf::RepeatedPtrField< ::FutureProto >*
      mutable_futures();

  // @@protoc_insertion_point(class_scope:PlayFunRequest)
 private:
  inline void set_has_current_state();
  inline void clear_has_current_state();
  inline void set_has_next();
  inline void clear_has_next();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* current_state_;
  ::std::string* next_;
  ::google::protobuf::RepeatedPtrField< ::FutureProto > futures_;
  friend void  protobuf_AddDesc_marionet_2eproto();
  friend void protobuf_AssignDesc_marionet_2eproto();
  friend void protobuf_ShutdownFile_marionet_2eproto();

  void InitAsDefaultInstance();
  static PlayFunRequest* default_instance_;
};
// -------------------------------------------------------------------

class PlayFunResponse : public ::google::protobuf::Message {
 public:
  PlayFunResponse();
  virtual ~PlayFunResponse();

  PlayFunResponse(const PlayFunResponse& from);

  inline PlayFunResponse& operator=(const PlayFunResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayFunResponse& default_instance();

  void Swap(PlayFunResponse* other);

  // implements Message ----------------------------------------------

  PlayFunResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayFunResponse& from);
  void MergeFrom(const PlayFunResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double immediate_score = 1;
  inline bool has_immediate_score() const;
  inline void clear_immediate_score();
  static const int kImmediateScoreFieldNumber = 1;
  inline double immediate_score() const;
  inline void set_immediate_score(double value);

  // optional double best_future_score = 2;
  inline bool has_best_future_score() const;
  inline void clear_best_future_score();
  static const int kBestFutureScoreFieldNumber = 2;
  inline double best_future_score() const;
  inline void set_best_future_score(double value);

  // optional double worst_future_score = 3;
  inline bool has_worst_future_score() const;
  inline void clear_worst_future_score();
  static const int kWorstFutureScoreFieldNumber = 3;
  inline double worst_future_score() const;
  inline void set_worst_future_score(double value);

  // optional double futures_score = 4;
  inline bool has_futures_score() const;
  inline void clear_futures_score();
  static const int kFuturesScoreFieldNumber = 4;
  inline double futures_score() const;
  inline void set_futures_score(double value);

  // repeated double futurescores = 5;
  inline int futurescores_size() const;
  inline void clear_futurescores();
  static const int kFuturescoresFieldNumber = 5;
  inline double futurescores(int index) const;
  inline void set_futurescores(int index, double value);
  inline void add_futurescores(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      futurescores() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_futurescores();

  // @@protoc_insertion_point(class_scope:PlayFunResponse)
 private:
  inline void set_has_immediate_score();
  inline void clear_has_immediate_score();
  inline void set_has_best_future_score();
  inline void clear_has_best_future_score();
  inline void set_has_worst_future_score();
  inline void clear_has_worst_future_score();
  inline void set_has_futures_score();
  inline void clear_has_futures_score();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double immediate_score_;
  double best_future_score_;
  double worst_future_score_;
  double futures_score_;
  ::google::protobuf::RepeatedField< double > futurescores_;
  friend void  protobuf_AddDesc_marionet_2eproto();
  friend void protobuf_AssignDesc_marionet_2eproto();
  friend void protobuf_ShutdownFile_marionet_2eproto();

  void InitAsDefaultInstance();
  static PlayFunResponse* default_instance_;
};
// -------------------------------------------------------------------

class TryImproveRequest : public ::google::protobuf::Message {
 public:
  TryImproveRequest();
  virtual ~TryImproveRequest();

  TryImproveRequest(const TryImproveRequest& from);

  inline TryImproveRequest& operator=(const TryImproveRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TryImproveRequest& default_instance();

  void Swap(TryImproveRequest* other);

  // implements Message ----------------------------------------------

  TryImproveRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TryImproveRequest& from);
  void MergeFrom(const TryImproveRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TryImproveRequest_Approach Approach;
  static const Approach RANDOM = TryImproveRequest_Approach_RANDOM;
  static const Approach OPPOSITES = TryImproveRequest_Approach_OPPOSITES;
  static const Approach ABLATION = TryImproveRequest_Approach_ABLATION;
  static const Approach CHOP = TryImproveRequest_Approach_CHOP;
  static inline bool Approach_IsValid(int value) {
    return TryImproveRequest_Approach_IsValid(value);
  }
  static const Approach Approach_MIN =
    TryImproveRequest_Approach_Approach_MIN;
  static const Approach Approach_MAX =
    TryImproveRequest_Approach_Approach_MAX;
  static const int Approach_ARRAYSIZE =
    TryImproveRequest_Approach_Approach_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Approach_descriptor() {
    return TryImproveRequest_Approach_descriptor();
  }
  static inline const ::std::string& Approach_Name(Approach value) {
    return TryImproveRequest_Approach_Name(value);
  }
  static inline bool Approach_Parse(const ::std::string& name,
      Approach* value) {
    return TryImproveRequest_Approach_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional bytes start_state = 1;
  inline bool has_start_state() const;
  inline void clear_start_state();
  static const int kStartStateFieldNumber = 1;
  inline const ::std::string& start_state() const;
  inline void set_start_state(const ::std::string& value);
  inline void set_start_state(const char* value);
  inline void set_start_state(const void* value, size_t size);
  inline ::std::string* mutable_start_state();
  inline ::std::string* release_start_state();
  inline void set_allocated_start_state(::std::string* start_state);

  // optional bytes improveme = 2;
  inline bool has_improveme() const;
  inline void clear_improveme();
  static const int kImprovemeFieldNumber = 2;
  inline const ::std::string& improveme() const;
  inline void set_improveme(const ::std::string& value);
  inline void set_improveme(const char* value);
  inline void set_improveme(const void* value, size_t size);
  inline ::std::string* mutable_improveme();
  inline ::std::string* release_improveme();
  inline void set_allocated_improveme(::std::string* improveme);

  // optional bytes end_state = 3;
  inline bool has_end_state() const;
  inline void clear_end_state();
  static const int kEndStateFieldNumber = 3;
  inline const ::std::string& end_state() const;
  inline void set_end_state(const ::std::string& value);
  inline void set_end_state(const char* value);
  inline void set_end_state(const void* value, size_t size);
  inline ::std::string* mutable_end_state();
  inline ::std::string* release_end_state();
  inline void set_allocated_end_state(::std::string* end_state);

  // optional double end_integral = 4;
  inline bool has_end_integral() const;
  inline void clear_end_integral();
  static const int kEndIntegralFieldNumber = 4;
  inline double end_integral() const;
  inline void set_end_integral(double value);

  // optional .TryImproveRequest.Approach approach = 5;
  inline bool has_approach() const;
  inline void clear_approach();
  static const int kApproachFieldNumber = 5;
  inline ::TryImproveRequest_Approach approach() const;
  inline void set_approach(::TryImproveRequest_Approach value);

  // optional string seed = 6;
  inline bool has_seed() const;
  inline void clear_seed();
  static const int kSeedFieldNumber = 6;
  inline const ::std::string& seed() const;
  inline void set_seed(const ::std::string& value);
  inline void set_seed(const char* value);
  inline void set_seed(const char* value, size_t size);
  inline ::std::string* mutable_seed();
  inline ::std::string* release_seed();
  inline void set_allocated_seed(::std::string* seed);

  // optional int32 iters = 7;
  inline bool has_iters() const;
  inline void clear_iters();
  static const int kItersFieldNumber = 7;
  inline ::google::protobuf::int32 iters() const;
  inline void set_iters(::google::protobuf::int32 value);

  // optional int32 maxbest = 8;
  inline bool has_maxbest() const;
  inline void clear_maxbest();
  static const int kMaxbestFieldNumber = 8;
  inline ::google::protobuf::int32 maxbest() const;
  inline void set_maxbest(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TryImproveRequest)
 private:
  inline void set_has_start_state();
  inline void clear_has_start_state();
  inline void set_has_improveme();
  inline void clear_has_improveme();
  inline void set_has_end_state();
  inline void clear_has_end_state();
  inline void set_has_end_integral();
  inline void clear_has_end_integral();
  inline void set_has_approach();
  inline void clear_has_approach();
  inline void set_has_seed();
  inline void clear_has_seed();
  inline void set_has_iters();
  inline void clear_has_iters();
  inline void set_has_maxbest();
  inline void clear_has_maxbest();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* start_state_;
  ::std::string* improveme_;
  ::std::string* end_state_;
  double end_integral_;
  ::std::string* seed_;
  int approach_;
  ::google::protobuf::int32 iters_;
  ::google::protobuf::int32 maxbest_;
  friend void  protobuf_AddDesc_marionet_2eproto();
  friend void protobuf_AssignDesc_marionet_2eproto();
  friend void protobuf_ShutdownFile_marionet_2eproto();

  void InitAsDefaultInstance();
  static TryImproveRequest* default_instance_;
};
// -------------------------------------------------------------------

class TryImproveResponse : public ::google::protobuf::Message {
 public:
  TryImproveResponse();
  virtual ~TryImproveResponse();

  TryImproveResponse(const TryImproveResponse& from);

  inline TryImproveResponse& operator=(const TryImproveResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TryImproveResponse& default_instance();

  void Swap(TryImproveResponse* other);

  // implements Message ----------------------------------------------

  TryImproveResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TryImproveResponse& from);
  void MergeFrom(const TryImproveResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes inputs = 1;
  inline int inputs_size() const;
  inline void clear_inputs();
  static const int kInputsFieldNumber = 1;
  inline const ::std::string& inputs(int index) const;
  inline ::std::string* mutable_inputs(int index);
  inline void set_inputs(int index, const ::std::string& value);
  inline void set_inputs(int index, const char* value);
  inline void set_inputs(int index, const void* value, size_t size);
  inline ::std::string* add_inputs();
  inline void add_inputs(const ::std::string& value);
  inline void add_inputs(const char* value);
  inline void add_inputs(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& inputs() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_inputs();

  // repeated double score = 2;
  inline int score_size() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 2;
  inline double score(int index) const;
  inline void set_score(int index, double value);
  inline void add_score(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      score() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_score();

  // optional int32 iters_tried = 3;
  inline bool has_iters_tried() const;
  inline void clear_iters_tried();
  static const int kItersTriedFieldNumber = 3;
  inline ::google::protobuf::int32 iters_tried() const;
  inline void set_iters_tried(::google::protobuf::int32 value);

  // optional int32 iters_better = 4;
  inline bool has_iters_better() const;
  inline void clear_iters_better();
  static const int kItersBetterFieldNumber = 4;
  inline ::google::protobuf::int32 iters_better() const;
  inline void set_iters_better(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TryImproveResponse)
 private:
  inline void set_has_iters_tried();
  inline void clear_has_iters_tried();
  inline void set_has_iters_better();
  inline void clear_has_iters_better();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> inputs_;
  ::google::protobuf::RepeatedField< double > score_;
  ::google::protobuf::int32 iters_tried_;
  ::google::protobuf::int32 iters_better_;
  friend void  protobuf_AddDesc_marionet_2eproto();
  friend void protobuf_AssignDesc_marionet_2eproto();
  friend void protobuf_ShutdownFile_marionet_2eproto();

  void InitAsDefaultInstance();
  static TryImproveResponse* default_instance_;
};
// -------------------------------------------------------------------

class HelperRequest : public ::google::protobuf::Message {
 public:
  HelperRequest();
  virtual ~HelperRequest();

  HelperRequest(const HelperRequest& from);

  inline HelperRequest& operator=(const HelperRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HelperRequest& default_instance();

  void Swap(HelperRequest* other);

  // implements Message ----------------------------------------------

  HelperRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HelperRequest& from);
  void MergeFrom(const HelperRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .PlayFunRequest playfun = 1;
  inline bool has_playfun() const;
  inline void clear_playfun();
  static const int kPlayfunFieldNumber = 1;
  inline const ::PlayFunRequest& playfun() const;
  inline ::PlayFunRequest* mutable_playfun();
  inline ::PlayFunRequest* release_playfun();
  inline void set_allocated_playfun(::PlayFunRequest* playfun);

  // optional .TryImproveRequest tryimprove = 2;
  inline bool has_tryimprove() const;
  inline void clear_tryimprove();
  static const int kTryimproveFieldNumber = 2;
  inline const ::TryImproveRequest& tryimprove() const;
  inline ::TryImproveRequest* mutable_tryimprove();
  inline ::TryImproveRequest* release_tryimprove();
  inline void set_allocated_tryimprove(::TryImproveRequest* tryimprove);

  // @@protoc_insertion_point(class_scope:HelperRequest)
 private:
  inline void set_has_playfun();
  inline void clear_has_playfun();
  inline void set_has_tryimprove();
  inline void clear_has_tryimprove();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::PlayFunRequest* playfun_;
  ::TryImproveRequest* tryimprove_;
  friend void  protobuf_AddDesc_marionet_2eproto();
  friend void protobuf_AssignDesc_marionet_2eproto();
  friend void protobuf_ShutdownFile_marionet_2eproto();

  void InitAsDefaultInstance();
  static HelperRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// MarkovInput

// -------------------------------------------------------------------

// FutureProto

// optional bytes inputs = 4;
inline bool FutureProto::has_inputs() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FutureProto::set_has_inputs() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FutureProto::clear_has_inputs() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FutureProto::clear_inputs() {
  if (inputs_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    inputs_->clear();
  }
  clear_has_inputs();
}
inline const ::std::string& FutureProto::inputs() const {
  // @@protoc_insertion_point(field_get:FutureProto.inputs)
  return *inputs_;
}
inline void FutureProto::set_inputs(const ::std::string& value) {
  set_has_inputs();
  if (inputs_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    inputs_ = new ::std::string;
  }
  inputs_->assign(value);
  // @@protoc_insertion_point(field_set:FutureProto.inputs)
}
inline void FutureProto::set_inputs(const char* value) {
  set_has_inputs();
  if (inputs_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    inputs_ = new ::std::string;
  }
  inputs_->assign(value);
  // @@protoc_insertion_point(field_set_char:FutureProto.inputs)
}
inline void FutureProto::set_inputs(const void* value, size_t size) {
  set_has_inputs();
  if (inputs_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    inputs_ = new ::std::string;
  }
  inputs_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:FutureProto.inputs)
}
inline ::std::string* FutureProto::mutable_inputs() {
  set_has_inputs();
  if (inputs_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    inputs_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:FutureProto.inputs)
  return inputs_;
}
inline ::std::string* FutureProto::release_inputs() {
  clear_has_inputs();
  if (inputs_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = inputs_;
    inputs_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void FutureProto::set_allocated_inputs(::std::string* inputs) {
  if (inputs_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete inputs_;
  }
  if (inputs) {
    set_has_inputs();
    inputs_ = inputs;
  } else {
    clear_has_inputs();
    inputs_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:FutureProto.inputs)
}

// -------------------------------------------------------------------

// PlayFunRequest

// optional bytes current_state = 1;
inline bool PlayFunRequest::has_current_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayFunRequest::set_has_current_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayFunRequest::clear_has_current_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayFunRequest::clear_current_state() {
  if (current_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    current_state_->clear();
  }
  clear_has_current_state();
}
inline const ::std::string& PlayFunRequest::current_state() const {
  // @@protoc_insertion_point(field_get:PlayFunRequest.current_state)
  return *current_state_;
}
inline void PlayFunRequest::set_current_state(const ::std::string& value) {
  set_has_current_state();
  if (current_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    current_state_ = new ::std::string;
  }
  current_state_->assign(value);
  // @@protoc_insertion_point(field_set:PlayFunRequest.current_state)
}
inline void PlayFunRequest::set_current_state(const char* value) {
  set_has_current_state();
  if (current_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    current_state_ = new ::std::string;
  }
  current_state_->assign(value);
  // @@protoc_insertion_point(field_set_char:PlayFunRequest.current_state)
}
inline void PlayFunRequest::set_current_state(const void* value, size_t size) {
  set_has_current_state();
  if (current_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    current_state_ = new ::std::string;
  }
  current_state_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PlayFunRequest.current_state)
}
inline ::std::string* PlayFunRequest::mutable_current_state() {
  set_has_current_state();
  if (current_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    current_state_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:PlayFunRequest.current_state)
  return current_state_;
}
inline ::std::string* PlayFunRequest::release_current_state() {
  clear_has_current_state();
  if (current_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = current_state_;
    current_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PlayFunRequest::set_allocated_current_state(::std::string* current_state) {
  if (current_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete current_state_;
  }
  if (current_state) {
    set_has_current_state();
    current_state_ = current_state;
  } else {
    clear_has_current_state();
    current_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:PlayFunRequest.current_state)
}

// optional bytes next = 2;
inline bool PlayFunRequest::has_next() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayFunRequest::set_has_next() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayFunRequest::clear_has_next() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayFunRequest::clear_next() {
  if (next_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    next_->clear();
  }
  clear_has_next();
}
inline const ::std::string& PlayFunRequest::next() const {
  // @@protoc_insertion_point(field_get:PlayFunRequest.next)
  return *next_;
}
inline void PlayFunRequest::set_next(const ::std::string& value) {
  set_has_next();
  if (next_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    next_ = new ::std::string;
  }
  next_->assign(value);
  // @@protoc_insertion_point(field_set:PlayFunRequest.next)
}
inline void PlayFunRequest::set_next(const char* value) {
  set_has_next();
  if (next_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    next_ = new ::std::string;
  }
  next_->assign(value);
  // @@protoc_insertion_point(field_set_char:PlayFunRequest.next)
}
inline void PlayFunRequest::set_next(const void* value, size_t size) {
  set_has_next();
  if (next_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    next_ = new ::std::string;
  }
  next_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PlayFunRequest.next)
}
inline ::std::string* PlayFunRequest::mutable_next() {
  set_has_next();
  if (next_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    next_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:PlayFunRequest.next)
  return next_;
}
inline ::std::string* PlayFunRequest::release_next() {
  clear_has_next();
  if (next_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = next_;
    next_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PlayFunRequest::set_allocated_next(::std::string* next) {
  if (next_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete next_;
  }
  if (next) {
    set_has_next();
    next_ = next;
  } else {
    clear_has_next();
    next_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:PlayFunRequest.next)
}

// repeated .FutureProto futures = 3;
inline int PlayFunRequest::futures_size() const {
  return futures_.size();
}
inline void PlayFunRequest::clear_futures() {
  futures_.Clear();
}
inline const ::FutureProto& PlayFunRequest::futures(int index) const {
  // @@protoc_insertion_point(field_get:PlayFunRequest.futures)
  return futures_.Get(index);
}
inline ::FutureProto* PlayFunRequest::mutable_futures(int index) {
  // @@protoc_insertion_point(field_mutable:PlayFunRequest.futures)
  return futures_.Mutable(index);
}
inline ::FutureProto* PlayFunRequest::add_futures() {
  // @@protoc_insertion_point(field_add:PlayFunRequest.futures)
  return futures_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::FutureProto >&
PlayFunRequest::futures() const {
  // @@protoc_insertion_point(field_list:PlayFunRequest.futures)
  return futures_;
}
inline ::google::protobuf::RepeatedPtrField< ::FutureProto >*
PlayFunRequest::mutable_futures() {
  // @@protoc_insertion_point(field_mutable_list:PlayFunRequest.futures)
  return &futures_;
}

// -------------------------------------------------------------------

// PlayFunResponse

// optional double immediate_score = 1;
inline bool PlayFunResponse::has_immediate_score() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayFunResponse::set_has_immediate_score() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayFunResponse::clear_has_immediate_score() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayFunResponse::clear_immediate_score() {
  immediate_score_ = 0;
  clear_has_immediate_score();
}
inline double PlayFunResponse::immediate_score() const {
  // @@protoc_insertion_point(field_get:PlayFunResponse.immediate_score)
  return immediate_score_;
}
inline void PlayFunResponse::set_immediate_score(double value) {
  set_has_immediate_score();
  immediate_score_ = value;
  // @@protoc_insertion_point(field_set:PlayFunResponse.immediate_score)
}

// optional double best_future_score = 2;
inline bool PlayFunResponse::has_best_future_score() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayFunResponse::set_has_best_future_score() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayFunResponse::clear_has_best_future_score() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayFunResponse::clear_best_future_score() {
  best_future_score_ = 0;
  clear_has_best_future_score();
}
inline double PlayFunResponse::best_future_score() const {
  // @@protoc_insertion_point(field_get:PlayFunResponse.best_future_score)
  return best_future_score_;
}
inline void PlayFunResponse::set_best_future_score(double value) {
  set_has_best_future_score();
  best_future_score_ = value;
  // @@protoc_insertion_point(field_set:PlayFunResponse.best_future_score)
}

// optional double worst_future_score = 3;
inline bool PlayFunResponse::has_worst_future_score() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlayFunResponse::set_has_worst_future_score() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlayFunResponse::clear_has_worst_future_score() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlayFunResponse::clear_worst_future_score() {
  worst_future_score_ = 0;
  clear_has_worst_future_score();
}
inline double PlayFunResponse::worst_future_score() const {
  // @@protoc_insertion_point(field_get:PlayFunResponse.worst_future_score)
  return worst_future_score_;
}
inline void PlayFunResponse::set_worst_future_score(double value) {
  set_has_worst_future_score();
  worst_future_score_ = value;
  // @@protoc_insertion_point(field_set:PlayFunResponse.worst_future_score)
}

// optional double futures_score = 4;
inline bool PlayFunResponse::has_futures_score() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PlayFunResponse::set_has_futures_score() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PlayFunResponse::clear_has_futures_score() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PlayFunResponse::clear_futures_score() {
  futures_score_ = 0;
  clear_has_futures_score();
}
inline double PlayFunResponse::futures_score() const {
  // @@protoc_insertion_point(field_get:PlayFunResponse.futures_score)
  return futures_score_;
}
inline void PlayFunResponse::set_futures_score(double value) {
  set_has_futures_score();
  futures_score_ = value;
  // @@protoc_insertion_point(field_set:PlayFunResponse.futures_score)
}

// repeated double futurescores = 5;
inline int PlayFunResponse::futurescores_size() const {
  return futurescores_.size();
}
inline void PlayFunResponse::clear_futurescores() {
  futurescores_.Clear();
}
inline double PlayFunResponse::futurescores(int index) const {
  // @@protoc_insertion_point(field_get:PlayFunResponse.futurescores)
  return futurescores_.Get(index);
}
inline void PlayFunResponse::set_futurescores(int index, double value) {
  futurescores_.Set(index, value);
  // @@protoc_insertion_point(field_set:PlayFunResponse.futurescores)
}
inline void PlayFunResponse::add_futurescores(double value) {
  futurescores_.Add(value);
  // @@protoc_insertion_point(field_add:PlayFunResponse.futurescores)
}
inline const ::google::protobuf::RepeatedField< double >&
PlayFunResponse::futurescores() const {
  // @@protoc_insertion_point(field_list:PlayFunResponse.futurescores)
  return futurescores_;
}
inline ::google::protobuf::RepeatedField< double >*
PlayFunResponse::mutable_futurescores() {
  // @@protoc_insertion_point(field_mutable_list:PlayFunResponse.futurescores)
  return &futurescores_;
}

// -------------------------------------------------------------------

// TryImproveRequest

// optional bytes start_state = 1;
inline bool TryImproveRequest::has_start_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TryImproveRequest::set_has_start_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TryImproveRequest::clear_has_start_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TryImproveRequest::clear_start_state() {
  if (start_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_state_->clear();
  }
  clear_has_start_state();
}
inline const ::std::string& TryImproveRequest::start_state() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.start_state)
  return *start_state_;
}
inline void TryImproveRequest::set_start_state(const ::std::string& value) {
  set_has_start_state();
  if (start_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_state_ = new ::std::string;
  }
  start_state_->assign(value);
  // @@protoc_insertion_point(field_set:TryImproveRequest.start_state)
}
inline void TryImproveRequest::set_start_state(const char* value) {
  set_has_start_state();
  if (start_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_state_ = new ::std::string;
  }
  start_state_->assign(value);
  // @@protoc_insertion_point(field_set_char:TryImproveRequest.start_state)
}
inline void TryImproveRequest::set_start_state(const void* value, size_t size) {
  set_has_start_state();
  if (start_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_state_ = new ::std::string;
  }
  start_state_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TryImproveRequest.start_state)
}
inline ::std::string* TryImproveRequest::mutable_start_state() {
  set_has_start_state();
  if (start_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    start_state_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:TryImproveRequest.start_state)
  return start_state_;
}
inline ::std::string* TryImproveRequest::release_start_state() {
  clear_has_start_state();
  if (start_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = start_state_;
    start_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TryImproveRequest::set_allocated_start_state(::std::string* start_state) {
  if (start_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete start_state_;
  }
  if (start_state) {
    set_has_start_state();
    start_state_ = start_state;
  } else {
    clear_has_start_state();
    start_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:TryImproveRequest.start_state)
}

// optional bytes improveme = 2;
inline bool TryImproveRequest::has_improveme() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TryImproveRequest::set_has_improveme() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TryImproveRequest::clear_has_improveme() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TryImproveRequest::clear_improveme() {
  if (improveme_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    improveme_->clear();
  }
  clear_has_improveme();
}
inline const ::std::string& TryImproveRequest::improveme() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.improveme)
  return *improveme_;
}
inline void TryImproveRequest::set_improveme(const ::std::string& value) {
  set_has_improveme();
  if (improveme_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    improveme_ = new ::std::string;
  }
  improveme_->assign(value);
  // @@protoc_insertion_point(field_set:TryImproveRequest.improveme)
}
inline void TryImproveRequest::set_improveme(const char* value) {
  set_has_improveme();
  if (improveme_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    improveme_ = new ::std::string;
  }
  improveme_->assign(value);
  // @@protoc_insertion_point(field_set_char:TryImproveRequest.improveme)
}
inline void TryImproveRequest::set_improveme(const void* value, size_t size) {
  set_has_improveme();
  if (improveme_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    improveme_ = new ::std::string;
  }
  improveme_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TryImproveRequest.improveme)
}
inline ::std::string* TryImproveRequest::mutable_improveme() {
  set_has_improveme();
  if (improveme_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    improveme_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:TryImproveRequest.improveme)
  return improveme_;
}
inline ::std::string* TryImproveRequest::release_improveme() {
  clear_has_improveme();
  if (improveme_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = improveme_;
    improveme_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TryImproveRequest::set_allocated_improveme(::std::string* improveme) {
  if (improveme_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete improveme_;
  }
  if (improveme) {
    set_has_improveme();
    improveme_ = improveme;
  } else {
    clear_has_improveme();
    improveme_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:TryImproveRequest.improveme)
}

// optional bytes end_state = 3;
inline bool TryImproveRequest::has_end_state() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TryImproveRequest::set_has_end_state() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TryImproveRequest::clear_has_end_state() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TryImproveRequest::clear_end_state() {
  if (end_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_state_->clear();
  }
  clear_has_end_state();
}
inline const ::std::string& TryImproveRequest::end_state() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.end_state)
  return *end_state_;
}
inline void TryImproveRequest::set_end_state(const ::std::string& value) {
  set_has_end_state();
  if (end_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_state_ = new ::std::string;
  }
  end_state_->assign(value);
  // @@protoc_insertion_point(field_set:TryImproveRequest.end_state)
}
inline void TryImproveRequest::set_end_state(const char* value) {
  set_has_end_state();
  if (end_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_state_ = new ::std::string;
  }
  end_state_->assign(value);
  // @@protoc_insertion_point(field_set_char:TryImproveRequest.end_state)
}
inline void TryImproveRequest::set_end_state(const void* value, size_t size) {
  set_has_end_state();
  if (end_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_state_ = new ::std::string;
  }
  end_state_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TryImproveRequest.end_state)
}
inline ::std::string* TryImproveRequest::mutable_end_state() {
  set_has_end_state();
  if (end_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    end_state_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:TryImproveRequest.end_state)
  return end_state_;
}
inline ::std::string* TryImproveRequest::release_end_state() {
  clear_has_end_state();
  if (end_state_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = end_state_;
    end_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TryImproveRequest::set_allocated_end_state(::std::string* end_state) {
  if (end_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete end_state_;
  }
  if (end_state) {
    set_has_end_state();
    end_state_ = end_state;
  } else {
    clear_has_end_state();
    end_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:TryImproveRequest.end_state)
}

// optional double end_integral = 4;
inline bool TryImproveRequest::has_end_integral() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TryImproveRequest::set_has_end_integral() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TryImproveRequest::clear_has_end_integral() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TryImproveRequest::clear_end_integral() {
  end_integral_ = 0;
  clear_has_end_integral();
}
inline double TryImproveRequest::end_integral() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.end_integral)
  return end_integral_;
}
inline void TryImproveRequest::set_end_integral(double value) {
  set_has_end_integral();
  end_integral_ = value;
  // @@protoc_insertion_point(field_set:TryImproveRequest.end_integral)
}

// optional .TryImproveRequest.Approach approach = 5;
inline bool TryImproveRequest::has_approach() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TryImproveRequest::set_has_approach() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TryImproveRequest::clear_has_approach() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TryImproveRequest::clear_approach() {
  approach_ = 0;
  clear_has_approach();
}
inline ::TryImproveRequest_Approach TryImproveRequest::approach() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.approach)
  return static_cast< ::TryImproveRequest_Approach >(approach_);
}
inline void TryImproveRequest::set_approach(::TryImproveRequest_Approach value) {
  assert(::TryImproveRequest_Approach_IsValid(value));
  set_has_approach();
  approach_ = value;
  // @@protoc_insertion_point(field_set:TryImproveRequest.approach)
}

// optional string seed = 6;
inline bool TryImproveRequest::has_seed() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TryImproveRequest::set_has_seed() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TryImproveRequest::clear_has_seed() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TryImproveRequest::clear_seed() {
  if (seed_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    seed_->clear();
  }
  clear_has_seed();
}
inline const ::std::string& TryImproveRequest::seed() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.seed)
  return *seed_;
}
inline void TryImproveRequest::set_seed(const ::std::string& value) {
  set_has_seed();
  if (seed_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    seed_ = new ::std::string;
  }
  seed_->assign(value);
  // @@protoc_insertion_point(field_set:TryImproveRequest.seed)
}
inline void TryImproveRequest::set_seed(const char* value) {
  set_has_seed();
  if (seed_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    seed_ = new ::std::string;
  }
  seed_->assign(value);
  // @@protoc_insertion_point(field_set_char:TryImproveRequest.seed)
}
inline void TryImproveRequest::set_seed(const char* value, size_t size) {
  set_has_seed();
  if (seed_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    seed_ = new ::std::string;
  }
  seed_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TryImproveRequest.seed)
}
inline ::std::string* TryImproveRequest::mutable_seed() {
  set_has_seed();
  if (seed_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    seed_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:TryImproveRequest.seed)
  return seed_;
}
inline ::std::string* TryImproveRequest::release_seed() {
  clear_has_seed();
  if (seed_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = seed_;
    seed_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TryImproveRequest::set_allocated_seed(::std::string* seed) {
  if (seed_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete seed_;
  }
  if (seed) {
    set_has_seed();
    seed_ = seed;
  } else {
    clear_has_seed();
    seed_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:TryImproveRequest.seed)
}

// optional int32 iters = 7;
inline bool TryImproveRequest::has_iters() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TryImproveRequest::set_has_iters() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TryImproveRequest::clear_has_iters() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TryImproveRequest::clear_iters() {
  iters_ = 0;
  clear_has_iters();
}
inline ::google::protobuf::int32 TryImproveRequest::iters() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.iters)
  return iters_;
}
inline void TryImproveRequest::set_iters(::google::protobuf::int32 value) {
  set_has_iters();
  iters_ = value;
  // @@protoc_insertion_point(field_set:TryImproveRequest.iters)
}

// optional int32 maxbest = 8;
inline bool TryImproveRequest::has_maxbest() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TryImproveRequest::set_has_maxbest() {
  _has_bits_[0] |= 0x00000080u;
}
inline void TryImproveRequest::clear_has_maxbest() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void TryImproveRequest::clear_maxbest() {
  maxbest_ = 0;
  clear_has_maxbest();
}
inline ::google::protobuf::int32 TryImproveRequest::maxbest() const {
  // @@protoc_insertion_point(field_get:TryImproveRequest.maxbest)
  return maxbest_;
}
inline void TryImproveRequest::set_maxbest(::google::protobuf::int32 value) {
  set_has_maxbest();
  maxbest_ = value;
  // @@protoc_insertion_point(field_set:TryImproveRequest.maxbest)
}

// -------------------------------------------------------------------

// TryImproveResponse

// repeated bytes inputs = 1;
inline int TryImproveResponse::inputs_size() const {
  return inputs_.size();
}
inline void TryImproveResponse::clear_inputs() {
  inputs_.Clear();
}
inline const ::std::string& TryImproveResponse::inputs(int index) const {
  // @@protoc_insertion_point(field_get:TryImproveResponse.inputs)
  return inputs_.Get(index);
}
inline ::std::string* TryImproveResponse::mutable_inputs(int index) {
  // @@protoc_insertion_point(field_mutable:TryImproveResponse.inputs)
  return inputs_.Mutable(index);
}
inline void TryImproveResponse::set_inputs(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:TryImproveResponse.inputs)
  inputs_.Mutable(index)->assign(value);
}
inline void TryImproveResponse::set_inputs(int index, const char* value) {
  inputs_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:TryImproveResponse.inputs)
}
inline void TryImproveResponse::set_inputs(int index, const void* value, size_t size) {
  inputs_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TryImproveResponse.inputs)
}
inline ::std::string* TryImproveResponse::add_inputs() {
  return inputs_.Add();
}
inline void TryImproveResponse::add_inputs(const ::std::string& value) {
  inputs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:TryImproveResponse.inputs)
}
inline void TryImproveResponse::add_inputs(const char* value) {
  inputs_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:TryImproveResponse.inputs)
}
inline void TryImproveResponse::add_inputs(const void* value, size_t size) {
  inputs_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:TryImproveResponse.inputs)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TryImproveResponse::inputs() const {
  // @@protoc_insertion_point(field_list:TryImproveResponse.inputs)
  return inputs_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TryImproveResponse::mutable_inputs() {
  // @@protoc_insertion_point(field_mutable_list:TryImproveResponse.inputs)
  return &inputs_;
}

// repeated double score = 2;
inline int TryImproveResponse::score_size() const {
  return score_.size();
}
inline void TryImproveResponse::clear_score() {
  score_.Clear();
}
inline double TryImproveResponse::score(int index) const {
  // @@protoc_insertion_point(field_get:TryImproveResponse.score)
  return score_.Get(index);
}
inline void TryImproveResponse::set_score(int index, double value) {
  score_.Set(index, value);
  // @@protoc_insertion_point(field_set:TryImproveResponse.score)
}
inline void TryImproveResponse::add_score(double value) {
  score_.Add(value);
  // @@protoc_insertion_point(field_add:TryImproveResponse.score)
}
inline const ::google::protobuf::RepeatedField< double >&
TryImproveResponse::score() const {
  // @@protoc_insertion_point(field_list:TryImproveResponse.score)
  return score_;
}
inline ::google::protobuf::RepeatedField< double >*
TryImproveResponse::mutable_score() {
  // @@protoc_insertion_point(field_mutable_list:TryImproveResponse.score)
  return &score_;
}

// optional int32 iters_tried = 3;
inline bool TryImproveResponse::has_iters_tried() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TryImproveResponse::set_has_iters_tried() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TryImproveResponse::clear_has_iters_tried() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TryImproveResponse::clear_iters_tried() {
  iters_tried_ = 0;
  clear_has_iters_tried();
}
inline ::google::protobuf::int32 TryImproveResponse::iters_tried() const {
  // @@protoc_insertion_point(field_get:TryImproveResponse.iters_tried)
  return iters_tried_;
}
inline void TryImproveResponse::set_iters_tried(::google::protobuf::int32 value) {
  set_has_iters_tried();
  iters_tried_ = value;
  // @@protoc_insertion_point(field_set:TryImproveResponse.iters_tried)
}

// optional int32 iters_better = 4;
inline bool TryImproveResponse::has_iters_better() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TryImproveResponse::set_has_iters_better() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TryImproveResponse::clear_has_iters_better() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TryImproveResponse::clear_iters_better() {
  iters_better_ = 0;
  clear_has_iters_better();
}
inline ::google::protobuf::int32 TryImproveResponse::iters_better() const {
  // @@protoc_insertion_point(field_get:TryImproveResponse.iters_better)
  return iters_better_;
}
inline void TryImproveResponse::set_iters_better(::google::protobuf::int32 value) {
  set_has_iters_better();
  iters_better_ = value;
  // @@protoc_insertion_point(field_set:TryImproveResponse.iters_better)
}

// -------------------------------------------------------------------

// HelperRequest

// optional .PlayFunRequest playfun = 1;
inline bool HelperRequest::has_playfun() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HelperRequest::set_has_playfun() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HelperRequest::clear_has_playfun() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HelperRequest::clear_playfun() {
  if (playfun_ != NULL) playfun_->::PlayFunRequest::Clear();
  clear_has_playfun();
}
inline const ::PlayFunRequest& HelperRequest::playfun() const {
  // @@protoc_insertion_point(field_get:HelperRequest.playfun)
  return playfun_ != NULL ? *playfun_ : *default_instance_->playfun_;
}
inline ::PlayFunRequest* HelperRequest::mutable_playfun() {
  set_has_playfun();
  if (playfun_ == NULL) playfun_ = new ::PlayFunRequest;
  // @@protoc_insertion_point(field_mutable:HelperRequest.playfun)
  return playfun_;
}
inline ::PlayFunRequest* HelperRequest::release_playfun() {
  clear_has_playfun();
  ::PlayFunRequest* temp = playfun_;
  playfun_ = NULL;
  return temp;
}
inline void HelperRequest::set_allocated_playfun(::PlayFunRequest* playfun) {
  delete playfun_;
  playfun_ = playfun;
  if (playfun) {
    set_has_playfun();
  } else {
    clear_has_playfun();
  }
  // @@protoc_insertion_point(field_set_allocated:HelperRequest.playfun)
}

// optional .TryImproveRequest tryimprove = 2;
inline bool HelperRequest::has_tryimprove() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HelperRequest::set_has_tryimprove() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HelperRequest::clear_has_tryimprove() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HelperRequest::clear_tryimprove() {
  if (tryimprove_ != NULL) tryimprove_->::TryImproveRequest::Clear();
  clear_has_tryimprove();
}
inline const ::TryImproveRequest& HelperRequest::tryimprove() const {
  // @@protoc_insertion_point(field_get:HelperRequest.tryimprove)
  return tryimprove_ != NULL ? *tryimprove_ : *default_instance_->tryimprove_;
}
inline ::TryImproveRequest* HelperRequest::mutable_tryimprove() {
  set_has_tryimprove();
  if (tryimprove_ == NULL) tryimprove_ = new ::TryImproveRequest;
  // @@protoc_insertion_point(field_mutable:HelperRequest.tryimprove)
  return tryimprove_;
}
inline ::TryImproveRequest* HelperRequest::release_tryimprove() {
  clear_has_tryimprove();
  ::TryImproveRequest* temp = tryimprove_;
  tryimprove_ = NULL;
  return temp;
}
inline void HelperRequest::set_allocated_tryimprove(::TryImproveRequest* tryimprove) {
  delete tryimprove_;
  tryimprove_ = tryimprove;
  if (tryimprove) {
    set_has_tryimprove();
  } else {
    clear_has_tryimprove();
  }
  // @@protoc_insertion_point(field_set_allocated:HelperRequest.tryimprove)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::TryImproveRequest_Approach> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TryImproveRequest_Approach>() {
  return ::TryImproveRequest_Approach_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_marionet_2eproto__INCLUDED
