// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marionet.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "marionet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MarkovInput_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MarkovInput_reflection_ = NULL;
const ::google::protobuf::Descriptor* FutureProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FutureProto_reflection_ = NULL;
const ::google::protobuf::Descriptor* PlayFunRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PlayFunRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* PlayFunResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PlayFunResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* TryImproveRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TryImproveRequest_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TryImproveRequest_Approach_descriptor_ = NULL;
const ::google::protobuf::Descriptor* TryImproveResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TryImproveResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* HelperRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HelperRequest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_marionet_2eproto() {
  protobuf_AddDesc_marionet_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "marionet.proto");
  GOOGLE_CHECK(file != NULL);
  MarkovInput_descriptor_ = file->message_type(0);
  static const int MarkovInput_offsets_[1] = {
  };
  MarkovInput_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MarkovInput_descriptor_,
      MarkovInput::default_instance_,
      MarkovInput_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkovInput, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MarkovInput, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MarkovInput));
  FutureProto_descriptor_ = file->message_type(1);
  static const int FutureProto_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FutureProto, inputs_),
  };
  FutureProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FutureProto_descriptor_,
      FutureProto::default_instance_,
      FutureProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FutureProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FutureProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FutureProto));
  PlayFunRequest_descriptor_ = file->message_type(2);
  static const int PlayFunRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunRequest, current_state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunRequest, next_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunRequest, futures_),
  };
  PlayFunRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PlayFunRequest_descriptor_,
      PlayFunRequest::default_instance_,
      PlayFunRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PlayFunRequest));
  PlayFunResponse_descriptor_ = file->message_type(3);
  static const int PlayFunResponse_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunResponse, immediate_score_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunResponse, best_future_score_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunResponse, worst_future_score_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunResponse, futures_score_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunResponse, futurescores_),
  };
  PlayFunResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PlayFunResponse_descriptor_,
      PlayFunResponse::default_instance_,
      PlayFunResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PlayFunResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PlayFunResponse));
  TryImproveRequest_descriptor_ = file->message_type(4);
  static const int TryImproveRequest_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, start_state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, improveme_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, end_state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, end_integral_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, approach_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, seed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, iters_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, maxbest_),
  };
  TryImproveRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TryImproveRequest_descriptor_,
      TryImproveRequest::default_instance_,
      TryImproveRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TryImproveRequest));
  TryImproveRequest_Approach_descriptor_ = TryImproveRequest_descriptor_->enum_type(0);
  TryImproveResponse_descriptor_ = file->message_type(5);
  static const int TryImproveResponse_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveResponse, inputs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveResponse, score_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveResponse, iters_tried_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveResponse, iters_better_),
  };
  TryImproveResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TryImproveResponse_descriptor_,
      TryImproveResponse::default_instance_,
      TryImproveResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TryImproveResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TryImproveResponse));
  HelperRequest_descriptor_ = file->message_type(6);
  static const int HelperRequest_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HelperRequest, playfun_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HelperRequest, tryimprove_),
  };
  HelperRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HelperRequest_descriptor_,
      HelperRequest::default_instance_,
      HelperRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HelperRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HelperRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HelperRequest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_marionet_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MarkovInput_descriptor_, &MarkovInput::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FutureProto_descriptor_, &FutureProto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PlayFunRequest_descriptor_, &PlayFunRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PlayFunResponse_descriptor_, &PlayFunResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TryImproveRequest_descriptor_, &TryImproveRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TryImproveResponse_descriptor_, &TryImproveResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HelperRequest_descriptor_, &HelperRequest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_marionet_2eproto() {
  delete MarkovInput::default_instance_;
  delete MarkovInput_reflection_;
  delete FutureProto::default_instance_;
  delete FutureProto_reflection_;
  delete PlayFunRequest::default_instance_;
  delete PlayFunRequest_reflection_;
  delete PlayFunResponse::default_instance_;
  delete PlayFunResponse_reflection_;
  delete TryImproveRequest::default_instance_;
  delete TryImproveRequest_reflection_;
  delete TryImproveResponse::default_instance_;
  delete TryImproveResponse_reflection_;
  delete HelperRequest::default_instance_;
  delete HelperRequest_reflection_;
}

void protobuf_AddDesc_marionet_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016marionet.proto\"\r\n\013MarkovInput\"\035\n\013Futur"
    "eProto\022\016\n\006inputs\030\004 \001(\014\"T\n\016PlayFunRequest"
    "\022\025\n\rcurrent_state\030\001 \001(\014\022\014\n\004next\030\002 \001(\014\022\035\n"
    "\007futures\030\003 \003(\0132\014.FutureProto\"\216\001\n\017PlayFun"
    "Response\022\027\n\017immediate_score\030\001 \001(\001\022\031\n\021bes"
    "t_future_score\030\002 \001(\001\022\032\n\022worst_future_sco"
    "re\030\003 \001(\001\022\025\n\rfutures_score\030\004 \001(\001\022\024\n\014futur"
    "escores\030\005 \003(\001\"\200\002\n\021TryImproveRequest\022\023\n\013s"
    "tart_state\030\001 \001(\014\022\021\n\timproveme\030\002 \001(\014\022\021\n\te"
    "nd_state\030\003 \001(\014\022\024\n\014end_integral\030\004 \001(\001\022-\n\010"
    "approach\030\005 \001(\0162\033.TryImproveRequest.Appro"
    "ach\022\014\n\004seed\030\006 \001(\t\022\r\n\005iters\030\007 \001(\005\022\017\n\007maxb"
    "est\030\010 \001(\005\"=\n\010Approach\022\n\n\006RANDOM\020\000\022\r\n\tOPP"
    "OSITES\020\001\022\014\n\010ABLATION\020\002\022\010\n\004CHOP\020\003\"^\n\022TryI"
    "mproveResponse\022\016\n\006inputs\030\001 \003(\014\022\r\n\005score\030"
    "\002 \003(\001\022\023\n\013iters_tried\030\003 \001(\005\022\024\n\014iters_bett"
    "er\030\004 \001(\005\"Y\n\rHelperRequest\022 \n\007playfun\030\001 \001"
    "(\0132\017.PlayFunRequest\022&\n\ntryimprove\030\002 \001(\0132"
    "\022.TryImproveRequest", 739);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "marionet.proto", &protobuf_RegisterTypes);
  MarkovInput::default_instance_ = new MarkovInput();
  FutureProto::default_instance_ = new FutureProto();
  PlayFunRequest::default_instance_ = new PlayFunRequest();
  PlayFunResponse::default_instance_ = new PlayFunResponse();
  TryImproveRequest::default_instance_ = new TryImproveRequest();
  TryImproveResponse::default_instance_ = new TryImproveResponse();
  HelperRequest::default_instance_ = new HelperRequest();
  MarkovInput::default_instance_->InitAsDefaultInstance();
  FutureProto::default_instance_->InitAsDefaultInstance();
  PlayFunRequest::default_instance_->InitAsDefaultInstance();
  PlayFunResponse::default_instance_->InitAsDefaultInstance();
  TryImproveRequest::default_instance_->InitAsDefaultInstance();
  TryImproveResponse::default_instance_->InitAsDefaultInstance();
  HelperRequest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_marionet_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_marionet_2eproto {
  StaticDescriptorInitializer_marionet_2eproto() {
    protobuf_AddDesc_marionet_2eproto();
  }
} static_descriptor_initializer_marionet_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

MarkovInput::MarkovInput()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MarkovInput)
}

void MarkovInput::InitAsDefaultInstance() {
}

MarkovInput::MarkovInput(const MarkovInput& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MarkovInput)
}

void MarkovInput::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MarkovInput::~MarkovInput() {
  // @@protoc_insertion_point(destructor:MarkovInput)
  SharedDtor();
}

void MarkovInput::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MarkovInput::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MarkovInput::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MarkovInput_descriptor_;
}

const MarkovInput& MarkovInput::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_marionet_2eproto();
  return *default_instance_;
}

MarkovInput* MarkovInput::default_instance_ = NULL;

MarkovInput* MarkovInput::New() const {
  return new MarkovInput;
}

void MarkovInput::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MarkovInput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MarkovInput)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:MarkovInput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MarkovInput)
  return false;
#undef DO_
}

void MarkovInput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MarkovInput)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MarkovInput)
}

::google::protobuf::uint8* MarkovInput::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MarkovInput)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MarkovInput)
  return target;
}

int MarkovInput::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MarkovInput::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MarkovInput* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MarkovInput*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MarkovInput::MergeFrom(const MarkovInput& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MarkovInput::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MarkovInput::CopyFrom(const MarkovInput& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MarkovInput::IsInitialized() const {

  return true;
}

void MarkovInput::Swap(MarkovInput* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MarkovInput::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MarkovInput_descriptor_;
  metadata.reflection = MarkovInput_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int FutureProto::kInputsFieldNumber;
#endif  // !_MSC_VER

FutureProto::FutureProto()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FutureProto)
}

void FutureProto::InitAsDefaultInstance() {
}

FutureProto::FutureProto(const FutureProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FutureProto)
}

void FutureProto::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  inputs_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FutureProto::~FutureProto() {
  // @@protoc_insertion_point(destructor:FutureProto)
  SharedDtor();
}

void FutureProto::SharedDtor() {
  if (inputs_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete inputs_;
  }
  if (this != default_instance_) {
  }
}

void FutureProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FutureProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FutureProto_descriptor_;
}

const FutureProto& FutureProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_marionet_2eproto();
  return *default_instance_;
}

FutureProto* FutureProto::default_instance_ = NULL;

FutureProto* FutureProto::New() const {
  return new FutureProto;
}

void FutureProto::Clear() {
  if (has_inputs()) {
    if (inputs_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      inputs_->clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FutureProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FutureProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes inputs = 4;
      case 4: {
        if (tag == 34) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_inputs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FutureProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FutureProto)
  return false;
#undef DO_
}

void FutureProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FutureProto)
  // optional bytes inputs = 4;
  if (has_inputs()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->inputs(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FutureProto)
}

::google::protobuf::uint8* FutureProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FutureProto)
  // optional bytes inputs = 4;
  if (has_inputs()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->inputs(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FutureProto)
  return target;
}

int FutureProto::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes inputs = 4;
    if (has_inputs()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->inputs());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FutureProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FutureProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FutureProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FutureProto::MergeFrom(const FutureProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_inputs()) {
      set_inputs(from.inputs());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FutureProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FutureProto::CopyFrom(const FutureProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FutureProto::IsInitialized() const {

  return true;
}

void FutureProto::Swap(FutureProto* other) {
  if (other != this) {
    std::swap(inputs_, other->inputs_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FutureProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FutureProto_descriptor_;
  metadata.reflection = FutureProto_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PlayFunRequest::kCurrentStateFieldNumber;
const int PlayFunRequest::kNextFieldNumber;
const int PlayFunRequest::kFuturesFieldNumber;
#endif  // !_MSC_VER

PlayFunRequest::PlayFunRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlayFunRequest)
}

void PlayFunRequest::InitAsDefaultInstance() {
}

PlayFunRequest::PlayFunRequest(const PlayFunRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PlayFunRequest)
}

void PlayFunRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  current_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  next_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PlayFunRequest::~PlayFunRequest() {
  // @@protoc_insertion_point(destructor:PlayFunRequest)
  SharedDtor();
}

void PlayFunRequest::SharedDtor() {
  if (current_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete current_state_;
  }
  if (next_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete next_;
  }
  if (this != default_instance_) {
  }
}

void PlayFunRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PlayFunRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PlayFunRequest_descriptor_;
}

const PlayFunRequest& PlayFunRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_marionet_2eproto();
  return *default_instance_;
}

PlayFunRequest* PlayFunRequest::default_instance_ = NULL;

PlayFunRequest* PlayFunRequest::New() const {
  return new PlayFunRequest;
}

void PlayFunRequest::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_current_state()) {
      if (current_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        current_state_->clear();
      }
    }
    if (has_next()) {
      if (next_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        next_->clear();
      }
    }
  }
  futures_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PlayFunRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlayFunRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes current_state = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_current_state()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_next;
        break;
      }

      // optional bytes next = 2;
      case 2: {
        if (tag == 18) {
         parse_next:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_next()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_futures;
        break;
      }

      // repeated .FutureProto futures = 3;
      case 3: {
        if (tag == 26) {
         parse_futures:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_futures()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_futures;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PlayFunRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlayFunRequest)
  return false;
#undef DO_
}

void PlayFunRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlayFunRequest)
  // optional bytes current_state = 1;
  if (has_current_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->current_state(), output);
  }

  // optional bytes next = 2;
  if (has_next()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->next(), output);
  }

  // repeated .FutureProto futures = 3;
  for (int i = 0; i < this->futures_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->futures(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PlayFunRequest)
}

::google::protobuf::uint8* PlayFunRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PlayFunRequest)
  // optional bytes current_state = 1;
  if (has_current_state()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->current_state(), target);
  }

  // optional bytes next = 2;
  if (has_next()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->next(), target);
  }

  // repeated .FutureProto futures = 3;
  for (int i = 0; i < this->futures_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->futures(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlayFunRequest)
  return target;
}

int PlayFunRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes current_state = 1;
    if (has_current_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->current_state());
    }

    // optional bytes next = 2;
    if (has_next()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->next());
    }

  }
  // repeated .FutureProto futures = 3;
  total_size += 1 * this->futures_size();
  for (int i = 0; i < this->futures_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->futures(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PlayFunRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PlayFunRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PlayFunRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PlayFunRequest::MergeFrom(const PlayFunRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  futures_.MergeFrom(from.futures_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_current_state()) {
      set_current_state(from.current_state());
    }
    if (from.has_next()) {
      set_next(from.next());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PlayFunRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayFunRequest::CopyFrom(const PlayFunRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayFunRequest::IsInitialized() const {

  return true;
}

void PlayFunRequest::Swap(PlayFunRequest* other) {
  if (other != this) {
    std::swap(current_state_, other->current_state_);
    std::swap(next_, other->next_);
    futures_.Swap(&other->futures_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PlayFunRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PlayFunRequest_descriptor_;
  metadata.reflection = PlayFunRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PlayFunResponse::kImmediateScoreFieldNumber;
const int PlayFunResponse::kBestFutureScoreFieldNumber;
const int PlayFunResponse::kWorstFutureScoreFieldNumber;
const int PlayFunResponse::kFuturesScoreFieldNumber;
const int PlayFunResponse::kFuturescoresFieldNumber;
#endif  // !_MSC_VER

PlayFunResponse::PlayFunResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PlayFunResponse)
}

void PlayFunResponse::InitAsDefaultInstance() {
}

PlayFunResponse::PlayFunResponse(const PlayFunResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PlayFunResponse)
}

void PlayFunResponse::SharedCtor() {
  _cached_size_ = 0;
  immediate_score_ = 0;
  best_future_score_ = 0;
  worst_future_score_ = 0;
  futures_score_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PlayFunResponse::~PlayFunResponse() {
  // @@protoc_insertion_point(destructor:PlayFunResponse)
  SharedDtor();
}

void PlayFunResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PlayFunResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PlayFunResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PlayFunResponse_descriptor_;
}

const PlayFunResponse& PlayFunResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_marionet_2eproto();
  return *default_instance_;
}

PlayFunResponse* PlayFunResponse::default_instance_ = NULL;

PlayFunResponse* PlayFunResponse::New() const {
  return new PlayFunResponse;
}

void PlayFunResponse::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<PlayFunResponse*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(immediate_score_, futures_score_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  futurescores_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PlayFunResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PlayFunResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double immediate_score = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &immediate_score_)));
          set_has_immediate_score();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_best_future_score;
        break;
      }

      // optional double best_future_score = 2;
      case 2: {
        if (tag == 17) {
         parse_best_future_score:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &best_future_score_)));
          set_has_best_future_score();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_worst_future_score;
        break;
      }

      // optional double worst_future_score = 3;
      case 3: {
        if (tag == 25) {
         parse_worst_future_score:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &worst_future_score_)));
          set_has_worst_future_score();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_futures_score;
        break;
      }

      // optional double futures_score = 4;
      case 4: {
        if (tag == 33) {
         parse_futures_score:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &futures_score_)));
          set_has_futures_score();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_futurescores;
        break;
      }

      // repeated double futurescores = 5;
      case 5: {
        if (tag == 41) {
         parse_futurescores:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 41, input, this->mutable_futurescores())));
        } else if (tag == 42) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_futurescores())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_futurescores;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PlayFunResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PlayFunResponse)
  return false;
#undef DO_
}

void PlayFunResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PlayFunResponse)
  // optional double immediate_score = 1;
  if (has_immediate_score()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->immediate_score(), output);
  }

  // optional double best_future_score = 2;
  if (has_best_future_score()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->best_future_score(), output);
  }

  // optional double worst_future_score = 3;
  if (has_worst_future_score()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->worst_future_score(), output);
  }

  // optional double futures_score = 4;
  if (has_futures_score()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->futures_score(), output);
  }

  // repeated double futurescores = 5;
  for (int i = 0; i < this->futurescores_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      5, this->futurescores(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PlayFunResponse)
}

::google::protobuf::uint8* PlayFunResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PlayFunResponse)
  // optional double immediate_score = 1;
  if (has_immediate_score()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->immediate_score(), target);
  }

  // optional double best_future_score = 2;
  if (has_best_future_score()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->best_future_score(), target);
  }

  // optional double worst_future_score = 3;
  if (has_worst_future_score()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->worst_future_score(), target);
  }

  // optional double futures_score = 4;
  if (has_futures_score()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->futures_score(), target);
  }

  // repeated double futurescores = 5;
  for (int i = 0; i < this->futurescores_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(5, this->futurescores(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlayFunResponse)
  return target;
}

int PlayFunResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional double immediate_score = 1;
    if (has_immediate_score()) {
      total_size += 1 + 8;
    }

    // optional double best_future_score = 2;
    if (has_best_future_score()) {
      total_size += 1 + 8;
    }

    // optional double worst_future_score = 3;
    if (has_worst_future_score()) {
      total_size += 1 + 8;
    }

    // optional double futures_score = 4;
    if (has_futures_score()) {
      total_size += 1 + 8;
    }

  }
  // repeated double futurescores = 5;
  {
    int data_size = 0;
    data_size = 8 * this->futurescores_size();
    total_size += 1 * this->futurescores_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PlayFunResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PlayFunResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PlayFunResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PlayFunResponse::MergeFrom(const PlayFunResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  futurescores_.MergeFrom(from.futurescores_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_immediate_score()) {
      set_immediate_score(from.immediate_score());
    }
    if (from.has_best_future_score()) {
      set_best_future_score(from.best_future_score());
    }
    if (from.has_worst_future_score()) {
      set_worst_future_score(from.worst_future_score());
    }
    if (from.has_futures_score()) {
      set_futures_score(from.futures_score());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PlayFunResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayFunResponse::CopyFrom(const PlayFunResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayFunResponse::IsInitialized() const {

  return true;
}

void PlayFunResponse::Swap(PlayFunResponse* other) {
  if (other != this) {
    std::swap(immediate_score_, other->immediate_score_);
    std::swap(best_future_score_, other->best_future_score_);
    std::swap(worst_future_score_, other->worst_future_score_);
    std::swap(futures_score_, other->futures_score_);
    futurescores_.Swap(&other->futurescores_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PlayFunResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PlayFunResponse_descriptor_;
  metadata.reflection = PlayFunResponse_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* TryImproveRequest_Approach_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TryImproveRequest_Approach_descriptor_;
}
bool TryImproveRequest_Approach_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const TryImproveRequest_Approach TryImproveRequest::RANDOM;
const TryImproveRequest_Approach TryImproveRequest::OPPOSITES;
const TryImproveRequest_Approach TryImproveRequest::ABLATION;
const TryImproveRequest_Approach TryImproveRequest::CHOP;
const TryImproveRequest_Approach TryImproveRequest::Approach_MIN;
const TryImproveRequest_Approach TryImproveRequest::Approach_MAX;
const int TryImproveRequest::Approach_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int TryImproveRequest::kStartStateFieldNumber;
const int TryImproveRequest::kImprovemeFieldNumber;
const int TryImproveRequest::kEndStateFieldNumber;
const int TryImproveRequest::kEndIntegralFieldNumber;
const int TryImproveRequest::kApproachFieldNumber;
const int TryImproveRequest::kSeedFieldNumber;
const int TryImproveRequest::kItersFieldNumber;
const int TryImproveRequest::kMaxbestFieldNumber;
#endif  // !_MSC_VER

TryImproveRequest::TryImproveRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:TryImproveRequest)
}

void TryImproveRequest::InitAsDefaultInstance() {
}

TryImproveRequest::TryImproveRequest(const TryImproveRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:TryImproveRequest)
}

void TryImproveRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  start_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  improveme_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  end_state_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  end_integral_ = 0;
  approach_ = 0;
  seed_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  iters_ = 0;
  maxbest_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TryImproveRequest::~TryImproveRequest() {
  // @@protoc_insertion_point(destructor:TryImproveRequest)
  SharedDtor();
}

void TryImproveRequest::SharedDtor() {
  if (start_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete start_state_;
  }
  if (improveme_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete improveme_;
  }
  if (end_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete end_state_;
  }
  if (seed_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete seed_;
  }
  if (this != default_instance_) {
  }
}

void TryImproveRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TryImproveRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TryImproveRequest_descriptor_;
}

const TryImproveRequest& TryImproveRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_marionet_2eproto();
  return *default_instance_;
}

TryImproveRequest* TryImproveRequest::default_instance_ = NULL;

TryImproveRequest* TryImproveRequest::New() const {
  return new TryImproveRequest;
}

void TryImproveRequest::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<TryImproveRequest*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(approach_, maxbest_);
    if (has_start_state()) {
      if (start_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        start_state_->clear();
      }
    }
    if (has_improveme()) {
      if (improveme_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        improveme_->clear();
      }
    }
    if (has_end_state()) {
      if (end_state_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        end_state_->clear();
      }
    }
    end_integral_ = 0;
    if (has_seed()) {
      if (seed_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        seed_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TryImproveRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TryImproveRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes start_state = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_start_state()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_improveme;
        break;
      }

      // optional bytes improveme = 2;
      case 2: {
        if (tag == 18) {
         parse_improveme:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_improveme()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_end_state;
        break;
      }

      // optional bytes end_state = 3;
      case 3: {
        if (tag == 26) {
         parse_end_state:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_end_state()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_end_integral;
        break;
      }

      // optional double end_integral = 4;
      case 4: {
        if (tag == 33) {
         parse_end_integral:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &end_integral_)));
          set_has_end_integral();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_approach;
        break;
      }

      // optional .TryImproveRequest.Approach approach = 5;
      case 5: {
        if (tag == 40) {
         parse_approach:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::TryImproveRequest_Approach_IsValid(value)) {
            set_approach(static_cast< ::TryImproveRequest_Approach >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_seed;
        break;
      }

      // optional string seed = 6;
      case 6: {
        if (tag == 50) {
         parse_seed:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_seed()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->seed().data(), this->seed().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "seed");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_iters;
        break;
      }

      // optional int32 iters = 7;
      case 7: {
        if (tag == 56) {
         parse_iters:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &iters_)));
          set_has_iters();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_maxbest;
        break;
      }

      // optional int32 maxbest = 8;
      case 8: {
        if (tag == 64) {
         parse_maxbest:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &maxbest_)));
          set_has_maxbest();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TryImproveRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TryImproveRequest)
  return false;
#undef DO_
}

void TryImproveRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TryImproveRequest)
  // optional bytes start_state = 1;
  if (has_start_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->start_state(), output);
  }

  // optional bytes improveme = 2;
  if (has_improveme()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->improveme(), output);
  }

  // optional bytes end_state = 3;
  if (has_end_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->end_state(), output);
  }

  // optional double end_integral = 4;
  if (has_end_integral()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->end_integral(), output);
  }

  // optional .TryImproveRequest.Approach approach = 5;
  if (has_approach()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->approach(), output);
  }

  // optional string seed = 6;
  if (has_seed()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->seed().data(), this->seed().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "seed");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->seed(), output);
  }

  // optional int32 iters = 7;
  if (has_iters()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->iters(), output);
  }

  // optional int32 maxbest = 8;
  if (has_maxbest()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->maxbest(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:TryImproveRequest)
}

::google::protobuf::uint8* TryImproveRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:TryImproveRequest)
  // optional bytes start_state = 1;
  if (has_start_state()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->start_state(), target);
  }

  // optional bytes improveme = 2;
  if (has_improveme()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->improveme(), target);
  }

  // optional bytes end_state = 3;
  if (has_end_state()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->end_state(), target);
  }

  // optional double end_integral = 4;
  if (has_end_integral()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->end_integral(), target);
  }

  // optional .TryImproveRequest.Approach approach = 5;
  if (has_approach()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->approach(), target);
  }

  // optional string seed = 6;
  if (has_seed()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->seed().data(), this->seed().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "seed");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->seed(), target);
  }

  // optional int32 iters = 7;
  if (has_iters()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->iters(), target);
  }

  // optional int32 maxbest = 8;
  if (has_maxbest()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->maxbest(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TryImproveRequest)
  return target;
}

int TryImproveRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes start_state = 1;
    if (has_start_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->start_state());
    }

    // optional bytes improveme = 2;
    if (has_improveme()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->improveme());
    }

    // optional bytes end_state = 3;
    if (has_end_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->end_state());
    }

    // optional double end_integral = 4;
    if (has_end_integral()) {
      total_size += 1 + 8;
    }

    // optional .TryImproveRequest.Approach approach = 5;
    if (has_approach()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->approach());
    }

    // optional string seed = 6;
    if (has_seed()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->seed());
    }

    // optional int32 iters = 7;
    if (has_iters()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->iters());
    }

    // optional int32 maxbest = 8;
    if (has_maxbest()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->maxbest());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TryImproveRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TryImproveRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TryImproveRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TryImproveRequest::MergeFrom(const TryImproveRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_start_state()) {
      set_start_state(from.start_state());
    }
    if (from.has_improveme()) {
      set_improveme(from.improveme());
    }
    if (from.has_end_state()) {
      set_end_state(from.end_state());
    }
    if (from.has_end_integral()) {
      set_end_integral(from.end_integral());
    }
    if (from.has_approach()) {
      set_approach(from.approach());
    }
    if (from.has_seed()) {
      set_seed(from.seed());
    }
    if (from.has_iters()) {
      set_iters(from.iters());
    }
    if (from.has_maxbest()) {
      set_maxbest(from.maxbest());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TryImproveRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TryImproveRequest::CopyFrom(const TryImproveRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TryImproveRequest::IsInitialized() const {

  return true;
}

void TryImproveRequest::Swap(TryImproveRequest* other) {
  if (other != this) {
    std::swap(start_state_, other->start_state_);
    std::swap(improveme_, other->improveme_);
    std::swap(end_state_, other->end_state_);
    std::swap(end_integral_, other->end_integral_);
    std::swap(approach_, other->approach_);
    std::swap(seed_, other->seed_);
    std::swap(iters_, other->iters_);
    std::swap(maxbest_, other->maxbest_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TryImproveRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TryImproveRequest_descriptor_;
  metadata.reflection = TryImproveRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TryImproveResponse::kInputsFieldNumber;
const int TryImproveResponse::kScoreFieldNumber;
const int TryImproveResponse::kItersTriedFieldNumber;
const int TryImproveResponse::kItersBetterFieldNumber;
#endif  // !_MSC_VER

TryImproveResponse::TryImproveResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:TryImproveResponse)
}

void TryImproveResponse::InitAsDefaultInstance() {
}

TryImproveResponse::TryImproveResponse(const TryImproveResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:TryImproveResponse)
}

void TryImproveResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  iters_tried_ = 0;
  iters_better_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TryImproveResponse::~TryImproveResponse() {
  // @@protoc_insertion_point(destructor:TryImproveResponse)
  SharedDtor();
}

void TryImproveResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TryImproveResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TryImproveResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TryImproveResponse_descriptor_;
}

const TryImproveResponse& TryImproveResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_marionet_2eproto();
  return *default_instance_;
}

TryImproveResponse* TryImproveResponse::default_instance_ = NULL;

TryImproveResponse* TryImproveResponse::New() const {
  return new TryImproveResponse;
}

void TryImproveResponse::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<TryImproveResponse*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(iters_tried_, iters_better_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  inputs_.Clear();
  score_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TryImproveResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TryImproveResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bytes inputs = 1;
      case 1: {
        if (tag == 10) {
         parse_inputs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_inputs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_inputs;
        if (input->ExpectTag(17)) goto parse_score;
        break;
      }

      // repeated double score = 2;
      case 2: {
        if (tag == 17) {
         parse_score:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 17, input, this->mutable_score())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_score())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_score;
        if (input->ExpectTag(24)) goto parse_iters_tried;
        break;
      }

      // optional int32 iters_tried = 3;
      case 3: {
        if (tag == 24) {
         parse_iters_tried:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &iters_tried_)));
          set_has_iters_tried();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_iters_better;
        break;
      }

      // optional int32 iters_better = 4;
      case 4: {
        if (tag == 32) {
         parse_iters_better:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &iters_better_)));
          set_has_iters_better();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TryImproveResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TryImproveResponse)
  return false;
#undef DO_
}

void TryImproveResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TryImproveResponse)
  // repeated bytes inputs = 1;
  for (int i = 0; i < this->inputs_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->inputs(i), output);
  }

  // repeated double score = 2;
  for (int i = 0; i < this->score_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      2, this->score(i), output);
  }

  // optional int32 iters_tried = 3;
  if (has_iters_tried()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->iters_tried(), output);
  }

  // optional int32 iters_better = 4;
  if (has_iters_better()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->iters_better(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:TryImproveResponse)
}

::google::protobuf::uint8* TryImproveResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:TryImproveResponse)
  // repeated bytes inputs = 1;
  for (int i = 0; i < this->inputs_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(1, this->inputs(i), target);
  }

  // repeated double score = 2;
  for (int i = 0; i < this->score_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(2, this->score(i), target);
  }

  // optional int32 iters_tried = 3;
  if (has_iters_tried()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->iters_tried(), target);
  }

  // optional int32 iters_better = 4;
  if (has_iters_better()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->iters_better(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TryImproveResponse)
  return target;
}

int TryImproveResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    // optional int32 iters_tried = 3;
    if (has_iters_tried()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->iters_tried());
    }

    // optional int32 iters_better = 4;
    if (has_iters_better()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->iters_better());
    }

  }
  // repeated bytes inputs = 1;
  total_size += 1 * this->inputs_size();
  for (int i = 0; i < this->inputs_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->inputs(i));
  }

  // repeated double score = 2;
  {
    int data_size = 0;
    data_size = 8 * this->score_size();
    total_size += 1 * this->score_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TryImproveResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TryImproveResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TryImproveResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TryImproveResponse::MergeFrom(const TryImproveResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  inputs_.MergeFrom(from.inputs_);
  score_.MergeFrom(from.score_);
  if (from._has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    if (from.has_iters_tried()) {
      set_iters_tried(from.iters_tried());
    }
    if (from.has_iters_better()) {
      set_iters_better(from.iters_better());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TryImproveResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TryImproveResponse::CopyFrom(const TryImproveResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TryImproveResponse::IsInitialized() const {

  return true;
}

void TryImproveResponse::Swap(TryImproveResponse* other) {
  if (other != this) {
    inputs_.Swap(&other->inputs_);
    score_.Swap(&other->score_);
    std::swap(iters_tried_, other->iters_tried_);
    std::swap(iters_better_, other->iters_better_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TryImproveResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TryImproveResponse_descriptor_;
  metadata.reflection = TryImproveResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int HelperRequest::kPlayfunFieldNumber;
const int HelperRequest::kTryimproveFieldNumber;
#endif  // !_MSC_VER

HelperRequest::HelperRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HelperRequest)
}

void HelperRequest::InitAsDefaultInstance() {
  playfun_ = const_cast< ::PlayFunRequest*>(&::PlayFunRequest::default_instance());
  tryimprove_ = const_cast< ::TryImproveRequest*>(&::TryImproveRequest::default_instance());
}

HelperRequest::HelperRequest(const HelperRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HelperRequest)
}

void HelperRequest::SharedCtor() {
  _cached_size_ = 0;
  playfun_ = NULL;
  tryimprove_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HelperRequest::~HelperRequest() {
  // @@protoc_insertion_point(destructor:HelperRequest)
  SharedDtor();
}

void HelperRequest::SharedDtor() {
  if (this != default_instance_) {
    delete playfun_;
    delete tryimprove_;
  }
}

void HelperRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HelperRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HelperRequest_descriptor_;
}

const HelperRequest& HelperRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_marionet_2eproto();
  return *default_instance_;
}

HelperRequest* HelperRequest::default_instance_ = NULL;

HelperRequest* HelperRequest::New() const {
  return new HelperRequest;
}

void HelperRequest::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_playfun()) {
      if (playfun_ != NULL) playfun_->::PlayFunRequest::Clear();
    }
    if (has_tryimprove()) {
      if (tryimprove_ != NULL) tryimprove_->::TryImproveRequest::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HelperRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:HelperRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .PlayFunRequest playfun = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_playfun()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_tryimprove;
        break;
      }

      // optional .TryImproveRequest tryimprove = 2;
      case 2: {
        if (tag == 18) {
         parse_tryimprove:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_tryimprove()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HelperRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HelperRequest)
  return false;
#undef DO_
}

void HelperRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HelperRequest)
  // optional .PlayFunRequest playfun = 1;
  if (has_playfun()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->playfun(), output);
  }

  // optional .TryImproveRequest tryimprove = 2;
  if (has_tryimprove()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->tryimprove(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:HelperRequest)
}

::google::protobuf::uint8* HelperRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:HelperRequest)
  // optional .PlayFunRequest playfun = 1;
  if (has_playfun()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->playfun(), target);
  }

  // optional .TryImproveRequest tryimprove = 2;
  if (has_tryimprove()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->tryimprove(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HelperRequest)
  return target;
}

int HelperRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .PlayFunRequest playfun = 1;
    if (has_playfun()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->playfun());
    }

    // optional .TryImproveRequest tryimprove = 2;
    if (has_tryimprove()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->tryimprove());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HelperRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HelperRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HelperRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HelperRequest::MergeFrom(const HelperRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_playfun()) {
      mutable_playfun()->::PlayFunRequest::MergeFrom(from.playfun());
    }
    if (from.has_tryimprove()) {
      mutable_tryimprove()->::TryImproveRequest::MergeFrom(from.tryimprove());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HelperRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HelperRequest::CopyFrom(const HelperRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HelperRequest::IsInitialized() const {

  return true;
}

void HelperRequest::Swap(HelperRequest* other) {
  if (other != this) {
    std::swap(playfun_, other->playfun_);
    std::swap(tryimprove_, other->tryimprove_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HelperRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HelperRequest_descriptor_;
  metadata.reflection = HelperRequest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
